[qdrant-1M-1536]
database = "qdrant"
dataset = "dbpedia-entities-openai-1M/data"
dimension = 1536
table = "embeddings_1M_1536"
payload_idx = 2
embedding_idx = 3
train_start_idx = 0
train_stop_idx = 26
query_start_idx = 5
query_stop_idx = 15
top_k = 5
queries_to_run = 100000
index = false

[qdrant-1M-1536-indexed]
database = "qdrant"
dataset = "dbpedia-entities-openai-1M/data"
dimension = 1536
table = "embeddings_1M_1536_indexed"
payload_idx = 2
embedding_idx = 3
train_start_idx = 0
train_stop_idx = 26
query_start_idx = 5
query_stop_idx = 15
top_k = 5
queries_to_run = 100000
index = true

[lancedb-1M-1536]
database = "lance"
dataset = "dbpedia-entities-openai-1M/data"
dimension = 1536
table = "embeddings_1M_1536"
payload_idx = 2
embedding_idx = 3
train_start_idx = 0
train_stop_idx = 26
query_start_idx = 5
query_stop_idx = 15
top_k = 5
queries_to_run = 100000
index = false
