[qdrant-1M]
database = "qdrant"
dataset = "dbpedia-entities-openai-1M/data"
dimension = 1536
table = "embeddings_table"
payload_idx = 2
embedding_idx = 3

[qdrant-35M-768]
database = "qdrant"
dataset = "wikipedia-22-12-en-embeddings/data"
table = "embeddings_35M_768"
dimension = 768
payload_idx = 2
embedding_idx = 8
